export const LOGIN_AUTO = 'LOGIN_AUTO';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED'

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL'; 


export const LOGOUT = 'LOGOUT'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'


export const REGISTER = 'REGISTER'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAIL = 'GET_USER_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const REMOVE_FROM_CART_SUCCESS = 'REMOVE_FROM_CART_SUCCESS'

export const GET_ITEM_CART = 'GET_ITEM_CART'
export const GET_ITEM_CART_SUCCESS = 'GET_ITEM_CART_SUCCESS'
export const GET_ITEM_CART_FAIL = 'GET_ITEM_CART_FAIL'

export const GET_ITEM = 'GET_ITEM'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAIL = 'GET_ITEM_FAIL'

export const GET_ITEM_CAT = 'GET_ITEM_CAT'
export const GET_ITEM_CAT_SUCCESS = 'GET_ITEM_CAT_SUCCESS'
export const GET_ITEM_CAT_FAIL = 'GET_ITEM_CAT_FAIL'

export const GET_ITEM_FAVORITE = 'GET_ITEM_FAVORITE'
export const GET_ITEM_FAVORITE_SUCCESS = 'GET_ITEM_FAVORITE_SUCCESS'
export const GET_ITEM_FAVORITE_FAIL = 'GET_ITEM_FAVORITE_FAIL'

export const ADD_ITEM_FAVORITE = 'ADD_ITEM_FAVORITE'
export const ADD_ITEM_FAVORITE_SUCCESS = 'ADD_ITEM_FAVORITE_SUCCESS'

export const REMOVE_ITEM_FAVORITE = 'REMOVE_ITEM_FAVORITE'
export const REMOVE_ITEM_FAVORITE_SUCCESS = 'REMOVE_ITEM_FAVORITE_SUCCESS'

export const ADD_LOCATION = 'ADD_LOCATION'
export const ADD_LOCATION_SUCCESS = 'ADD_LOCATION_SUCCESS'

export const ADD_USERPHONE = 'ADD_USERPHONE'
export const ADD_USERPHONE_SUCCESS = 'ADD_USERPHONE_SUCCESS'

